// <auto-generated />
namespace Makers.SmartParking.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Parkingplacestatusenumadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Parkingplacestatusenumadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201503140114575_Parking place status enum added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
