// <auto-generated />
namespace Makers.SmartParking.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CurrentStatusIdfiledfixedinParkingPlaceStatusChangetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CurrentStatusIdfiledfixedinParkingPlaceStatusChangetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201503140123136_CurrentStatusId filed fixed in ParkingPlaceStatusChange table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
